### 1. Sign Up a New User
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "full_name": "string",
  "phone": "string",
  "email": "user@example.com",
  "password": "string",
  "role": "buyer",
  "address": "string",
  "profileImageBase64": "string",
  "bank_info": {
    "bank_name": "string",
    "account_number": "string"
  }
}
### 2. Login a user
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "phone":"string",
  "password": "string"
}

