### 1. Sign Up a New User
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "name": "alice2",
  "familyName": "alicepass",
  "phone": "12345",
  "email": "",
  "password": "1234",
  "address": "1324"
}
