### 1. Sign Up a New User
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "fullName": "parsa esmaeili",
  "phone": "14",
  "email": "",
  "password": "1234",
  "address": "1324",
  "role": "BUYER"
}
### 2. Login a user
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "phone":"14",
  "password": "1234"
}

